- README.md
- appveyor.yml
Does not include tests, as those don't work yet.
> Configure appveyor build

- samples/aspnetcore/BasicSample/Controllers/HelloWorldController.cs
- samples/webapi/BasicODataWebApiSample/BasicODataWebApiSample.csproj
- samples/webapi/BasicODataWebApiSample/Controllers/OrdersController.cs
- samples/webapi/BasicODataWebApiSample/Controllers/People2Controller.cs
- samples/webapi/BasicODataWebApiSample/Controllers/PeopleController.cs
- samples/webapi/BasicODataWebApiSample/Startup.cs
- samples/webapi/BasicWebApiSample/Controllers/HelloWorldController.cs
- samples/webapi/ConventionsODataWebApiSample/Startup.cs
Updates the sample projects in preparation for the RTW 1.0 release.
> Update Samples for RTW

- src/Common/Versioning/ApiVersioningOptions.cs
- src/Microsoft.AspNet.WebApi.Versioning/Dispatcher/ApiVersionControllerSelector.cs
- src/Microsoft.AspNet.WebApi.Versioning/Dispatcher/HttpResponseExceptionFactory.cs
- src/Microsoft.AspNet.WebApi.Versioning/Versioning/ApiVersioningOptions.cs
- src/Microsoft.AspNet.WebApi.Versioning/Versioning/CreateBadRequestDelegate.cs
- src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersionActionSelector.cs
- src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersioningOptions.cs
- src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/BadRequestHandler.cs
- src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/CreateBadRequestDelegate.cs
- test/Microsoft.AspNet.WebApi.Versioning.Tests/Dispatcher/ApiVersionControllerSelectorTest.cs
Fixes the format of error responses for 400 errors related to API versions
> Fix Format of 400 Error Responses

- src/Microsoft.AspNet.WebApi.Versioning/Controllers/AggregatedActionMapping.cs
- src/Microsoft.AspNet.WebApi.Versioning/Controllers/ApiVersionActionSelector.cs
- src/Microsoft.AspNet.WebApi.Versioning/Dispatcher/ApiVersionControllerAggregator.cs
- src/Microsoft.AspNet.WebApi.Versioning/System.Web.Http/HttpControllerDescriptorExtensions.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/AcceptanceTest.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/Http/ByNamespace/ByNamespaceAcceptanceTest.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/Http/ByNamespace/Controllers/V1/HelloWorldController.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/Http/ByNamespace/Controllers/V2/HelloWorldController.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/Http/ByNamespace/Controllers/V3/HelloWorldController.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/Http/ByNamespace/given/a_query_string_versioned_ApiController_per_namespace.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/Http/ByNamespace/given/a_url_versioned_ApiController_per_namespace.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/Http/ByNamespace/given/a_url_versioned_and_attribute-routed_ApiController_per_namespace.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/OData/Advanced/AdvancedAcceptanceTest.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/OData/Advanced/Controllers/Orders3Controller.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/OData/ODataAcceptanceTest.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/AcceptanceTest.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Conventions/given/a_query_string_versioned_Controller_split_into_two_types_using_conventions.cs
Fixes a scenario where the resolved action binding does not match the correct, matched controller. This PR also adds new test coverage to prevent future regression.
> Fix InvalidCastException

- ApiVersioningWithSamples.sln
- samples/webapi/AdvancedODataWebApiSample/Controllers/Orders3Controller.cs
- samples/webapi/AdvancedODataWebApiSample/Controllers/OrdersController.cs
- samples/webapi/AdvancedODataWebApiSample/Startup.cs
Updates the advanced OData example and also includes the acceptance tests into the solution
> Update Advanced OData Example

- src/Microsoft.AspNet.WebApi.Versioning/Versioning/Conventions/ControllerApiVersionConventionBuilderT.cs
- src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/Conventions/ControllerApiVersionConventionBuilderT.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/Http/Conventions/Controllers/HelloWorld2Controller.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/Http/Conventions/ConventionsAcceptanceTest.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/Http/Conventions/given/a_url_versioned_ApiController_using_conventions.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Conventions/Controllers/HelloWorld2Controller.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Conventions/ConventionsAcceptanceTest.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Conventions/given/a_url_versioned_Controller_using_conventions.cs
Fixes the reported API versions when conventions are used
> Fix Report API Versions By Convention

- src/Microsoft.AspNet.WebApi.Versioning/Dispatcher/ControllerSelector.cs
- src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersionActionSelector.cs
Removes the unused ApiVersionReader property from action and controller selectors
> Remove Unused ApiVersionReader Property

- src/Common/ApiVersionNeutralAttribute.cs
Fixes the inheritance of API version neutrality, when applied via attributes.
> Fix Inheritance of Version Neutrality

- ApiVersioningWithSamples.sln
- src/Common/Versioning/MediaTypeApiVersionReader.cs
- src/Common/Versioning/QueryStringApiVersionReader.cs
- src/Microsoft.AspNet.WebApi.Versioning/Versioning/MediaTypeApiVersionReader.cs
- src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/MediaTypeApiVersionReader.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/AcceptanceTest.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/Http/MediaTypeNegotiation/Controllers/HelloWorldController.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/Http/MediaTypeNegotiation/Controllers/Values2Controller.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/Http/MediaTypeNegotiation/Controllers/ValuesController.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/Http/MediaTypeNegotiation/MediaTypeNegotiationAcceptanceTest.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/Http/MediaTypeNegotiation/Models/Message.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/Http/MediaTypeNegotiation/given/an_ApiController_versioned_by_media_type_negotiation.cs
- test/Microsoft.AspNet.WebApi.Versioning.Tests/Versioning/MediaTypeApiVersionReaderTest.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/AcceptanceTest.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/MediaTypeNegotiation/Controllers/HelloWorldController.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/MediaTypeNegotiation/Controllers/Values2Controller.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/MediaTypeNegotiation/Controllers/ValuesController.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/MediaTypeNegotiation/MediaTypeNegotiationAcceptanceTest.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/MediaTypeNegotiation/Models/Message.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/MediaTypeNegotiation/given/a_Controller_versioned_by_media_type_negotiation.cs
- test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Versioning/Conventions/ControllerApiVersionConventionBuilderTTest.cs
- test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Versioning/MediaTypeApiVersionReaderTest.cs
Adds support for versioning by media type using the Accept and Content-Type HTTP headers.
> Add Support for Versioning by Media Type

- src/Microsoft.AspNetCore.Mvc.Versioning/Routing/DefaultApiVersionRoutePolicy.cs
- src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ActionSelectionResult.cs
- src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersionActionSelector.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/AcceptanceTest.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Basic/BasicAcceptanceTest.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Basic/Controllers/HelloWorld2Controller.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Basic/Controllers/HomeController.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Basic/Controllers/Values2Controller.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Basic/Controllers/ValuesController.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Basic/given a version-neutral UI Controller/when accessing a view.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Basic/given a versioned Controller/when using a query string and split into two types.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Basic/given a versioned Controller/when using a url segment.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Views/Home/Index.cshtml
- test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Versioning/TestApiVersionActionSelector.cs
These changes refactor the action selection process to address a number of regressions that occurred in the first 1.1 release candidate for ASP.NET Core. A number of new acceptance tests were also added to match reported issues and avoid future regressions.
> Fix 1.1 RC1 Action Selection Regression

- samples/aspnetcore/ByNamespaceSample/V3/Controllers/OrdersController.cs
> fix version (v3 instead of v1)

- ApiVersioningWithSamples.sln
- build.targets
- nuget.config
- samples/aspnetcore/BasicSample/BasicSample.csproj
- samples/aspnetcore/ByNamespaceSample/ByNamespaceSample.csproj
- samples/aspnetcore/ConventionsSample/ConventionsSample.csproj
- samples/aspnetcore/SwaggerSample/SwaggerSample.csproj
- src/Common/Versioning/MediaTypeApiVersionReader.cs
- src/Microsoft.AspNet.OData.Versioning.ApiExplorer/Microsoft.AspNet.OData.Versioning.ApiExplorer.csproj
- src/Microsoft.AspNet.OData.Versioning/Microsoft.AspNet.OData.Versioning.csproj
- src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/Microsoft.AspNet.WebApi.Versioning.ApiExplorer.csproj
- src/Microsoft.AspNet.WebApi.Versioning/Microsoft.AspNet.WebApi.Versioning.csproj
- src/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer/ApiVersionModelMetadata.cs
- src/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer.csproj
- src/Microsoft.AspNetCore.Mvc.Versioning/Microsoft.AspNetCore.Mvc.Versioning.csproj
- src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersionActionSelector.cs
- src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ILoggerExtensions.cs
- test/Microsoft.AspNet.OData.Versioning.ApiExplorer.Tests/Microsoft.AspNet.OData.Versioning.ApiExplorer.Tests.csproj
- test/Microsoft.AspNet.OData.Versioning.Tests/Microsoft.AspNet.OData.Versioning.Tests.csproj
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/Microsoft.AspNet.WebApi.Acceptance.Tests.csproj
- test/Microsoft.AspNet.WebApi.Versioning.ApiExplorer.Tests/Microsoft.AspNet.WebApi.Versioning.ApiExplorer.Tests.csproj
- test/Microsoft.AspNet.WebApi.Versioning.Tests/Microsoft.AspNet.WebApi.Versioning.Tests.csproj
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/AcceptanceTest.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Microsoft.AspNetCore.Mvc.Acceptance.Tests.csproj
- test/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer.Tests/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer.Tests.csproj
- test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Microsoft.AspNetCore.Mvc.Versioning.Tests.csproj
- test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Versioning/TestApiVersionActionSelector.cs
Adds support for ASP.NET Core 2.0
> Upgrade to ASP.NET Core 2.0

- src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/DefaultErrorResponseProvider.cs
Changes the default error response from a dictionary to an object in ASP.NET Core. This will ensure that the member casing of the serialized response content will match the default JSON settings in ASP.NET Core. Resolves #195.
> Change Error Response From Dictionary to Object

- src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersionActionSelector.cs
Minor change that will allow action selection from candidates that do not have API versioning conventions applied, such as Razor Pages. Fixes #189
> Support Razor Pages

- build/code-analysis.props
- src/Microsoft.AspNet.OData.Versioning.ApiExplorer/Microsoft.AspNet.OData.Versioning.ApiExplorer.csproj
- src/Microsoft.AspNet.OData.Versioning/Microsoft.AspNet.OData.Versioning.csproj
- src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/Microsoft.AspNet.WebApi.Versioning.ApiExplorer.csproj
- src/Microsoft.AspNet.WebApi.Versioning/Microsoft.AspNet.WebApi.Versioning.csproj
- src/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer.csproj
- src/Microsoft.AspNetCore.Mvc.Versioning/Microsoft.AspNetCore.Mvc.Versioning.csproj
- src/directory.build.props
- src/directory.build.targets
Simplifies the integration of code analysis and reduces the number of touch points during updates. Also updates the code analysis package to 2.6.0-beta2 as the currently used version is now broken with current version of Visual Studio.
> Update Code Analysis

- src/Common/Versioning/ApiVersionRequestProperties.cs
- src/Common/Versioning/UrlSegmentApiVersionReader.cs
- src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/Description/VersionedApiDescription.cs
- src/Microsoft.AspNet.WebApi.Versioning/Dispatcher/HttpResponseExceptionFactory.cs
- src/Microsoft.AspNet.WebApi.Versioning/Microsoft.AspNet.WebApi.Versioning.csproj
- src/Microsoft.AspNet.WebApi.Versioning/Routing/ApiVersionRouteConstraint.cs
- src/Microsoft.AspNet.WebApi.Versioning/System.Web.Http/HttpConfigurationExtensions.cs
- src/Microsoft.AspNet.WebApi.Versioning/System.Web.Http/HttpRequestMessageExtensions.cs
- src/Microsoft.AspNet.WebApi.Versioning/Versioning/ApiVersionRequestProperties.cs
- src/Microsoft.AspNet.WebApi.Versioning/Versioning/UrlSegmentApiVersionReader.cs
- src/Microsoft.AspNetCore.Mvc.Versioning/Microsoft.AspNetCore.Mvc.Versioning.csproj
- src/Microsoft.AspNetCore.Mvc.Versioning/Microsoft.Extensions.DependencyInjection/IServiceCollectionExtensions.cs
- src/Microsoft.AspNetCore.Mvc.Versioning/Routing/ApiVersionRouteConstraint.cs
- src/Microsoft.AspNetCore.Mvc.Versioning/Routing/DefaultApiVersionRoutePolicy.cs
- src/Microsoft.AspNetCore.Mvc.Versioning/SR.Designer.cs
- src/Microsoft.AspNetCore.Mvc.Versioning/SR.resx
- src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersionRequestProperties.cs
- src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/UrlSegmentApiVersionReader.cs
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/Http/Basic/given a version-neutral ApiController/when no version is specified.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Basic/given a version-neutral Controller/when no version is specified.cs
- test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Versioning/UrlSegmentApiVersionReaderTest.cs
Fix 405 error response instead of 400 with assume default version when unspecified. Fixes #254
> Fixes 405 Error Response with AssumeDefaultVersionWhenUnspecified

- .editorconfig
- src/Microsoft.AspNet.OData.Versioning.ApiExplorer/Description/ODataRouteBuilder.cs
- src/Microsoft.AspNet.OData.Versioning.ApiExplorer/Microsoft.AspNet.OData.Versioning.ApiExplorer.csproj
Corrects the link generation for convention-based OData controllers
> Fix OData Swagger Links

- ApiVersioning.sln
- README.md
- after.apiversioning.sln.targets
- build/common.props
- build/file-version.targets
- build/nuget.props
- build/signing.targets
- samples/webapi/directory.build.targets
- src/directory.build.targets
Add build support to enable official Microsoft Authenticode signing to assebmlies as well as signing of NuGet packages
> Enable Code Signing

- src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/Description/VersionedApiExplorer.cs
- src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/Microsoft.AspNet.WebApi.Versioning.ApiExplorer.csproj
Fix IControllerConfiguration recursion in Web API implementation of VersionedApiExplorer. Fixes #313.
> Fix IControllerConfiguration Recursion

- src/Microsoft.AspNet.OData.Versioning/Routing/VersionedAttributeRoutingConvention.cs
- src/Microsoft.AspNetCore.OData.Versioning/AspNet.OData/Routing/VersionedAttributeRoutingConvention.cs
- src/Microsoft.AspNetCore.OData.Versioning/AspNetCore.Mvc/Versioning/ODataApiVersionActionSelector.cs
Update route parameters and fix action selection. Fixes #336. Resolves #337. Resolves #341.
> Fix OData Core Action Selection

- src/Common.OData/Common.OData.projitems
Fix shared manifest resource name. Fixes #331
> Fix Shared OData *.resx

- src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersioningApplicationModelProvider.cs
- src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersioningOptions.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Microsoft.AspNetCore.Mvc.Acceptance.Tests.csproj
- test/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer.Tests/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer.Tests.csproj
- test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Microsoft.AspNetCore.Mvc.Versioning.Tests.csproj
- test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Versioning/ApiVersioningApplicationModelProviderTest.cs
- test/Microsoft.AspNetCore.OData.Versioning.ApiExplorer.Tests/Microsoft.AspNetCore.OData.Versioning.ApiExplorer.Tests.csproj
- test/Microsoft.AspNetCore.OData.Versioning.Tests/Microsoft.AspNetCore.OData.Versioning.Tests.csproj
- test/directory.build.props
Adds support for API Behaviors in ASP.NET Core 2.1+
> Support API Behaviors

- samples/aspnetcore/SwaggerODataSample/Properties/launchSettings.json
Obviously super small, but compiler warnings always annoy me.
Shameless attempt at earning an MS Hacktoberfest T-Shirt.
> Remove compiler warning of extra comma

- src/Common/Versioning/Conventions/VersionByNamespaceConvention.cs
- test/Microsoft.AspNet.WebApi.Versioning.Tests/Versioning/Conventions/VersionByNamespaceConventionTest.cs
- test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Versioning/Conventions/VersionByNamespaceConventionTest.cs
Fixes parsing of version from a namespace. Relates to #366
> Fix Parsing of Version from a Namespace

- samples/aspnetcore/BasicSample/BasicSample.csproj
- samples/aspnetcore/ByNamespaceSample/ByNamespaceSample.csproj
- samples/aspnetcore/ConventionsSample/ConventionsSample.csproj
- samples/aspnetcore/ODataBasicSample/ODataBasicSample.csproj
- samples/aspnetcore/SwaggerODataSample/SwaggerODataSample.csproj
- samples/aspnetcore/SwaggerSample/SwaggerSample.csproj
Update package dependencies to resolve security alerts in sample projects
> Update Package Dependencies in Sample Projects

- samples/aspnetcore/SwaggerODataSample/Startup.cs
- samples/aspnetcore/SwaggerSample/Startup.cs
Dispose of temporary service provider. Resolves #403
> Dispose of Temporary Service Provider

- samples/aspnetcore/BasicSample/Startup.cs
- samples/aspnetcore/ByNamespaceSample/Startup.cs
- samples/aspnetcore/ConventionsSample/Startup.cs
- samples/aspnetcore/ODataBasicSample/Startup.cs
- samples/aspnetcore/SwaggerODataSample/Startup.cs
- samples/aspnetcore/SwaggerSample/Startup.cs
> Fix spelling

- src/Microsoft.AspNetCore.Mvc.Versioning/Microsoft.AspNetCore.Mvc.Versioning.csproj
- src/Microsoft.AspNetCore.Mvc.Versioning/ReleaseNotes.txt
- src/Microsoft.AspNetCore.Mvc.Versioning/Routing/ApiVersionMatcherPolicy.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Mvc/Basic/given a versioned Controller/when using a query string and split into two types.cs
- test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Mvc/Basic/given a versioned Controller/when using a url segment.cs
- test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Routing/ApiVersionMatcherPolicyTest.cs
Fix endpoint policy for invalid candidate with matching API version. Fixes #423.
> Fix Endpoint Selection Policy

- src/Microsoft.AspNet.WebApi.Versioning/Dispatcher/ApiVersionControllerSelector.cs
- src/Microsoft.AspNet.WebApi.Versioning/Microsoft.AspNet.WebApi.Versioning.csproj
- src/Microsoft.AspNet.WebApi.Versioning/ReleaseNotes.txt
Fix enumeration of non-OWIN routes. Fixes #428
> Fix Enumeration of Non-OWIN Routes

- src/Common.OData.ApiExplorer/AspNet.OData/DefaultModelTypeBuilder.cs
Changes:
- Now resolves all dependencies on the first call to `NewStructuredType`.
- All types will always be built, see `ResolveDependencies`.
- Fixed a bug where a collection dependency would add itself as the type rather than the dependency.
I refactored the **DefaultModelTypeBuilder** to resolve all dependencies on the first call.
This is done by iterating through all structured types in the EdmModel. In most cases this will be faster assuming most entity types are used in the api endpoints. This prevents iterating through all generated types to resolve again for each structured type.
Because all structured types have been passed and there are no later dependencies all types of **TypeBuilder** can safely be built.
Hopefully this resolves the exception people are having. If not, we can …
> Refactored the DefaultModelTypeBuilder

- samples/aspnetcore/SwaggerODataSample/SwaggerDefaultValues.cs
- samples/aspnetcore/SwaggerSample/SwaggerDefaultValues.cs
- samples/webapi/SwaggerODataWebApiSample/SwaggerDefaultValues.cs
- samples/webapi/SwaggerWebApiSample/SwaggerDefaultValues.cs
- src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/Microsoft.AspNet.WebApi.Versioning.ApiExplorer.csproj
- src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/ReleaseNotes.txt
- src/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer.csproj
- src/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer/ReleaseNotes.txt
- src/Microsoft.AspNetCore.Mvc.Versioning/Microsoft.AspNetCore.Mvc.Versioning.csproj
- src/Microsoft.AspNetCore.Mvc.Versioning/ReleaseNotes.txt
- src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersionModelBinderProvider.cs
Fixes ApiVersion model binding in ASP.NET Core. Fixes #452
> Fix ApiVersion Model Binding

- src/Common/Versioning/IApiVersionReaderExtensions.cs
- src/Microsoft.AspNet.WebApi.Versioning/Microsoft.AspNet.WebApi.Versioning.csproj
- src/Microsoft.AspNet.WebApi.Versioning/ReleaseNotes.txt
- src/Microsoft.AspNetCore.Mvc.Versioning/Microsoft.AspNetCore.Mvc.Versioning.csproj
- src/Microsoft.AspNetCore.Mvc.Versioning/ReleaseNotes.txt
- src/Microsoft.AspNetCore.OData.Versioning/AspNet.OData/Routing/UnversionedODataPathRouteConstraint.cs
- src/Microsoft.AspNetCore.OData.Versioning/Microsoft.AspNetCore.OData.Versioning.csproj
- src/Microsoft.AspNetCore.OData.Versioning/ReleaseNotes.txt
Summary of changes
- Fixes media type parameter resolution
- Fixes NullReferenceException in UnversionedODataRouteConstraint
> OData Fixes 2019-08-10

- README.md
"You can additional find" -> "You can find additional"
> Fixed word order

- ApiVersioning.sln
- samples/webapi/AdvancedODataWebApiSample/Controllers/OrdersController.cs
- samples/webapi/AdvancedODataWebApiSample/Controllers/PeopleController.cs
- src/Common.ApiExplorer/ApiExplorerOptions.cs
- src/Common/Versioning/Conventions/ApiVersionConventionBuilderExtensions.cs
- src/Microsoft.AspNet.WebApi.Versioning/System.Web.Http/HttpActionDescriptorExtensions.cs
- src/Microsoft.AspNet.WebApi.Versioning/System.Web.Http/HttpRouteCollectionExtensions.cs
- src/Microsoft.AspNetCore.Mvc.Versioning/Abstractions/ActionDescriptorExtensions.cs
- test/Microsoft.AspNet.OData.Versioning.ApiExplorer.Tests/AspNet.OData/DefaultModelTypeBuilderTest.cs
- test/Microsoft.AspNet.WebApi.Versioning.Tests/Routing/ApiVersionRouteConstraintTest.cs
- test/Microsoft.AspNet.WebApi.Versioning.Tests/System.Web.Http/HttpActionDescriptorExtensionsTest.cs
- test/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer.Tests/DefaultApiVersionDescriptionProviderTest.cs
- test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Routing/ApiVersionRouteConstraintTest.cs
- test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Versioning/ApiVersioningRouteOptionsSetupTest.cs
- test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Versioning/UrlSegmentApiVersionReaderTest.cs
- test/Microsoft.AspNetCore.OData.Versioning.ApiExplorer.Tests/AspNet.OData/DefaultModelTypeBuilderTest.cs
- test/Microsoft.AspNetCore.OData.Versioning.Tests/AspNetCore.Mvc/ApplicationModels/ODataControllerSpecificationTest.cs
While looking through examples, I took the time to fix some typos.
> Fixed typos

- src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/Description/VersionedApiExplorer.cs
- src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/ReleaseNotes.txt
- src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/Routing/IParsedRoute.cs
- src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/Routing/ParsedRouteAdapter{T}.cs
Handle model bound API version in route template. Fixes #671
> Handle Model Bound API Version in Route Template

- src/Microsoft.AspNetCore.Mvc.Versioning/Routing/ApiVersionMatcherPolicy.cs
> RC Fixes Round 2

- asp.sln
- examples/AspNet/OData/OpenApiODataWebApiExample/ODataExtensions.cs
- examples/AspNet/OData/OpenApiODataWebApiExample/V3/AcmeController.cs
- examples/AspNet/OData/OpenApiODataWebApiExample/V3/ProductsController.cs
- examples/AspNet/OData/OpenApiODataWebApiExample/V3/SuppliersController.cs
- examples/AspNetCore/OData/ODataOpenApiExample/ODataExtensions.cs
- examples/AspNetCore/OData/ODataOpenApiExample/V3/AcmeController.cs
- examples/AspNetCore/OData/ODataOpenApiExample/V3/ProductsController.cs
- examples/AspNetCore/OData/ODataOpenApiExample/V3/SuppliersController.cs
- src/AspNet/Directory.Build.targets
- src/AspNet/OData/src/Asp.Versioning.WebApi.OData.ApiExplorer/ApiExplorer/ODataApiExplorer.cs
- src/AspNet/OData/src/Asp.Versioning.WebApi.OData.ApiExplorer/Asp.Versioning.WebApi.OData.ApiExplorer.csproj
- src/AspNet/OData/src/Asp.Versioning.WebApi.OData/Asp.Versioning.WebApi.OData.csproj
- src/AspNet/WebApi/src/Asp.Versioning.WebApi.ApiExplorer/ApiExplorer/VersionedApiExplorer.cs
- src/AspNet/WebApi/src/Asp.Versioning.WebApi.ApiExplorer/Asp.Versioning.WebApi.ApiExplorer.csproj
- src/AspNet/WebApi/src/Asp.Versioning.WebApi/Asp.Versioning.WebApi.csproj
- src/AspNet/WebApi/src/Asp.Versioning.WebApi/Dispatcher/ApiVersionControllerSelector.cs
- src/AspNet/WebApi/test/Asp.Versioning.WebApi.ApiExplorer.Tests/Asp.Versioning.WebApi.ApiExplorer.Tests.csproj
- Simplify build for full .NET Framework reference assemblies
- Update OData examples to show extracting a related key from a URI
> Update OData Examples

- src/Common.OData.ApiExplorer/AspNet.OData/Routing/ODataRouteBuilderContext.cs
> Added support for "~/entityset/cast" and "~/entityset/key/cast" routing conventions

- .github/workflows/codeql-analysis.yml
- src/Abstractions/src/Asp.Versioning.Abstractions/ApiVersion.cs
- src/Abstractions/src/Asp.Versioning.Abstractions/ApiVersionFormatProvider.cs
- src/Abstractions/src/Asp.Versioning.Abstractions/FormatTokenizer.cs
- src/Abstractions/src/Asp.Versioning.Abstractions/NamespaceParser.cs
- src/AspNet/OData/src/Asp.Versioning.WebApi.OData.ApiExplorer/Routing/ODataRouteBuilder.cs
- src/AspNet/OData/src/Asp.Versioning.WebApi.OData.ApiExplorer/System.Web.Http/HttpConfigurationExtensions.cs
- src/AspNet/WebApi/src/Asp.Versioning.WebApi.ApiExplorer/ApiExplorer/VersionedApiExplorer.cs
- src/AspNet/WebApi/src/Asp.Versioning.WebApi.ApiExplorer/Routing/ParsedRouteAdapter{T}.cs
- src/AspNet/WebApi/src/Asp.Versioning.WebApi.ApiExplorer/Routing/PathContentSegmentAdapter{T}.cs
- src/AspNet/WebApi/src/Asp.Versioning.WebApi/ApiVersionRequestProperties.cs
- src/AspNet/WebApi/src/Asp.Versioning.WebApi/Controllers/ActionSelectorCacheItem.cs
- src/AspNet/WebApi/src/Asp.Versioning.WebApi/Conventions/ActionApiVersionConventionBuilderBase.cs
- src/AspNet/WebApi/src/Asp.Versioning.WebApi/DefaultApiVersionReporter.cs
- src/AspNet/WebApi/src/Asp.Versioning.WebApi/Dispatcher/ApiVersionControllerSelector.cs
- src/AspNet/WebApi/src/Asp.Versioning.WebApi/Dispatcher/HttpResponseExceptionFactory.cs
- src/AspNet/WebApi/src/Asp.Versioning.WebApi/System.Net.Http/HttpResponseMessageExtensions.cs
- src/AspNet/WebApi/src/Asp.Versioning.WebApi/System.Web.Http/HttpRouteExtensions.cs
- src/AspNetCore/OData/src/Asp.Versioning.OData.ApiExplorer/ApiExplorer/ODataApiDescriptionProvider.cs
- src/AspNetCore/WebApi/src/Asp.Versioning.Http/ApiVersioningFeature.cs
- src/AspNetCore/WebApi/src/Asp.Versioning.Http/net6.0/Builder/VersionedEndpointConventionBuilder.cs
- src/AspNetCore/WebApi/src/Asp.Versioning.Http/net6.0/DefaultApiVersionReporter.cs
- src/AspNetCore/WebApi/src/Asp.Versioning.Http/netcoreapp3.1/DefaultApiVersionReporter.cs
- src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/DefaultApiVersionDescriptionProvider.cs
- src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/ApiVersionCollator.cs
- src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/ApplyContentTypeVersionActionFilter.cs
- src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/Conventions/ActionApiVersionConventionBuilderBase.cs
- src/Common/src/Common.OData.ApiExplorer/Conventions/ODataQueryOptionsConventionBuilder.cs
Fix pending CodeQL warnings and suggestions.
https://github.com/dotnet/aspnet-api-versioning/security/code-scanning
> Fix CodeQL Warnings and Suggestions

- src/AspNet/WebApi/src/Asp.Versioning.WebApi/System.Net.Http/HttpResponseMessageExtensions.cs
Revision; fixes CodeQL suggestions
https://github.com/dotnet/aspnet-api-versioning/security/code-scanning
> Fix CodeQL Suggestion (Rev 1)

- test/Microsoft.AspNet.OData.Versioning.ApiExplorer.Tests/Microsoft.AspNet.OData.Versioning.ApiExplorer.Tests.csproj
- test/Microsoft.AspNet.OData.Versioning.Tests/Microsoft.AspNet.OData.Versioning.Tests.csproj
- test/Microsoft.AspNet.WebApi.Acceptance.Tests/Microsoft.AspNet.WebApi.Acceptance.Tests.csproj
- test/Microsoft.AspNet.WebApi.Versioning.ApiExplorer.Tests/Microsoft.AspNet.WebApi.Versioning.ApiExplorer.Tests.csproj
- test/Microsoft.AspNet.WebApi.Versioning.Tests/Microsoft.AspNet.WebApi.Versioning.Tests.csproj
Dependabot suggestions for `release/5.0`, but should only apply to `release/5.1` and above.
Resolves #872
> Fix Dependabot Reference Suggestions

- src/AspNet/OData/src/Asp.Versioning.WebApi.OData.ApiExplorer/Asp.Versioning.WebApi.OData.ApiExplorer.csproj
- src/AspNet/OData/src/Asp.Versioning.WebApi.OData.ApiExplorer/ReleaseNotes.txt
- src/AspNet/OData/src/Asp.Versioning.WebApi.OData/Asp.Versioning.WebApi.OData.csproj
- src/AspNet/OData/src/Asp.Versioning.WebApi.OData/ReleaseNotes.txt
- src/AspNet/WebApi/src/Asp.Versioning.WebApi.ApiExplorer/Asp.Versioning.WebApi.ApiExplorer.csproj
- src/AspNet/WebApi/src/Asp.Versioning.WebApi.ApiExplorer/Description/ApiVersionParameterDescriptionContext.cs
- src/AspNet/WebApi/src/Asp.Versioning.WebApi.ApiExplorer/ReleaseNotes.txt
- src/AspNet/WebApi/src/Asp.Versioning.WebApi/ApplyContentTypeVersionActionFilter.cs
- src/AspNet/WebApi/src/Asp.Versioning.WebApi/Asp.Versioning.WebApi.csproj
- src/AspNet/WebApi/src/Asp.Versioning.WebApi/ReleaseNotes.txt
- src/AspNet/WebApi/src/Asp.Versioning.WebApi/System.Web.Http/HttpConfigurationExtensions.cs
- src/AspNetCore/OData/src/Asp.Versioning.OData.ApiExplorer/Asp.Versioning.OData.ApiExplorer.csproj
- src/AspNetCore/OData/src/Asp.Versioning.OData.ApiExplorer/ReleaseNotes.txt
- src/AspNetCore/OData/src/Asp.Versioning.OData/Asp.Versioning.OData.csproj
- src/AspNetCore/OData/src/Asp.Versioning.OData/ReleaseNotes.txt
- src/AspNetCore/WebApi/src/Asp.Versioning.Http/Asp.Versioning.Http.csproj
- src/AspNetCore/WebApi/src/Asp.Versioning.Http/ReleaseNotes.txt
- src/AspNetCore/WebApi/src/Asp.Versioning.Http/net6.0/Builder/IEndpointConventionBuilderExtensions.cs
- src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/ApiVersionParameterDescriptionContext.cs
- src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/Asp.Versioning.Mvc.ApiExplorer.csproj
- src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/ReleaseNotes.txt
- src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/ApiVersioningMvcOptionsSetup.cs
- src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/Asp.Versioning.Mvc.csproj
- src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/ReleaseNotes.txt
- src/Client/test/Asp.Versioning.Http.Client.Tests/TestServer.cs
- src/Common/src/Common/MediaTypeApiVersionReaderBuilder.cs
> Fix MediaTypeApiVersionReaderBuilder.AddParameters

- src/AspNetCore/Acceptance/Asp.Versioning.Mvc.Acceptance.Tests/Http/InteropFixture.cs
- src/AspNetCore/Acceptance/Asp.Versioning.Mvc.Acceptance.Tests/Http/MinimalApiFixture.cs
- src/AspNetCore/Acceptance/Asp.Versioning.Mvc.Acceptance.Tests/Http/given a versioned minimal API/when error objects are enabled.cs
- src/AspNetCore/Acceptance/Asp.Versioning.Mvc.Acceptance.Tests/Mvc/UsingAttributes/InteropFixture.cs
- src/AspNetCore/Acceptance/Asp.Versioning.Mvc.Acceptance.Tests/Mvc/UsingAttributes/given a versioned Controller/when error objects are enabled.cs
- src/AspNetCore/WebApi/src/Asp.Versioning.Http/Asp.Versioning.Http.csproj
- src/AspNetCore/WebApi/src/Asp.Versioning.Http/ErrorObjectFactory.cs
- src/AspNetCore/WebApi/src/Asp.Versioning.Http/ReleaseNotes.txt
- src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/DependencyInjection/IApiVersioningBuilderExtensions.cs
- src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/MvcProblemDetailsFactory.cs
Back ports **Error Object** support to the `6.x` release.
Related to #1019
> Back Port Error Object Support

- src/AspNet/OData/src/Asp.Versioning.WebApi.OData.ApiExplorer/Asp.Versioning.WebApi.OData.ApiExplorer.csproj
- src/AspNet/OData/src/Asp.Versioning.WebApi.OData.ApiExplorer/ReleaseNotes.txt
- src/AspNet/OData/src/Asp.Versioning.WebApi.OData/Asp.Versioning.WebApi.OData.csproj
- src/AspNet/OData/src/Asp.Versioning.WebApi.OData/ReleaseNotes.txt
- src/AspNet/WebApi/src/Asp.Versioning.WebApi.ApiExplorer/Asp.Versioning.WebApi.ApiExplorer.csproj
- src/AspNet/WebApi/src/Asp.Versioning.WebApi.ApiExplorer/ReleaseNotes.txt
- src/AspNet/WebApi/src/Asp.Versioning.WebApi/ReleaseNotes.txt
- src/AspNetCore/OData/src/Asp.Versioning.OData.ApiExplorer/Asp.Versioning.OData.ApiExplorer.csproj
- src/AspNetCore/OData/src/Asp.Versioning.OData.ApiExplorer/ReleaseNotes.txt
- src/AspNetCore/OData/src/Asp.Versioning.OData/Asp.Versioning.OData.csproj
- src/AspNetCore/OData/src/Asp.Versioning.OData/ReleaseNotes.txt
- src/AspNetCore/WebApi/src/Asp.Versioning.Http/ReleaseNotes.txt
- src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/Asp.Versioning.Mvc.ApiExplorer.csproj
- src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/ReleaseNotes.txt
- src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/Asp.Versioning.Mvc.csproj
- src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/ReleaseNotes.txt
Prepares the necessary changes for the 7.1 release.
> Prepare 7.1 Release

- build/nuget.props
- examples/AspNet/WebApi/BasicWebApiExample/Controllers/Values2Controller.cs
- examples/AspNet/WebApi/ConventionsWebApiExample/Controllers/Values2Controller.cs
- src/Directory.Build.targets
Minimum changes required to build the solution using the .NET 8 SDK tooling.
> Fix .NET 8 Tooling

- README.md
Summary of the changes (Less than 80 chars)
Move .net core packages to the top in Readme.
> Move .net core packages to the top.

- src/Abstractions/src/Asp.Versioning.Abstractions/Asp.Versioning.Abstractions.csproj
- src/Abstractions/src/Asp.Versioning.Abstractions/ReleaseNotes.txt
- src/AspNetCore/OData/src/Asp.Versioning.OData.ApiExplorer/Asp.Versioning.OData.ApiExplorer.csproj
- src/AspNetCore/OData/src/Asp.Versioning.OData/Asp.Versioning.OData.csproj
- src/AspNetCore/WebApi/src/Asp.Versioning.Http/Asp.Versioning.Http.csproj
- src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/Asp.Versioning.Mvc.ApiExplorer.csproj
- src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/Asp.Versioning.Mvc.csproj
- src/Client/src/Asp.Versioning.Http.Client/Asp.Versioning.Http.Client.csproj
- src/Client/src/Asp.Versioning.Http.Client/ReleaseNotes.txt
Preparing the 8.1 release.
- Bump version numbers
- Update release notes
> Prepare 8.1 Release

- examples/AspNet/OData/OpenApiODataWebApiExample/Startup.cs
- examples/AspNet/OData/SomeOpenApiODataWebApiExample/Startup.cs
- examples/AspNet/WebApi/OpenApiWebApiExample/Startup.cs
- examples/AspNetCore/OData/ODataOpenApiExample/ConfigureSwaggerOptions.cs
- examples/AspNetCore/OData/SomeODataOpenApiExample/ConfigureSwaggerOptions.cs
- examples/AspNetCore/WebApi/MinimalOpenApiExample/ConfigureSwaggerOptions.cs
- examples/AspNetCore/WebApi/OpenApiExample/ConfigureSwaggerOptions.cs
Render fancier Swagger UI links. These changes only apply to project examples.
> Render Fancier Swagger UI Links
