dotnet/aspnet-api-versioning

src/Microsoft.AspNet.WebApi.Versioning/System.Web.Http/HttpConfigurationExtensions.cs, src/Microsoft.AspNet.WebApi.Versioning/System.Web.Http/HttpRequestMessageExtensions.cs, src/Microsoft.AspNet.WebApi.Versioning/Versioning/ApiVersionModel.cs
Consolidate all methods of retrieving the configured API versioning options to a single extension method on HttpConfiguration and a shortcut extension method on HttpRequestMessage. This opens up access to all configured options and supplants to need for extension methods that retrieve only specific API versioning options.
=> Consolidate all methods of retrieving API versioning options

src/Microsoft.AspNet.OData.Versioning/Web.OData/Routing/VersionedODataPathRouteConstraint.cs, test/Microsoft.AspNet.OData.Versioning.Tests/Web.OData/Routing/VersionedODataPathRouteConstraintTest.cs
This fixes the **VersionedODataRouteConstraint**. The correct API version will now be matched to service documents, metadata, and OData controllers when using implicit API versioning.
=> Fixed Versioned OData Route Constraint

src/Microsoft.AspNet.WebApi.Versioning/Controllers/ActionSelectionResult.cs, src/Microsoft.AspNet.WebApi.Versioning/Controllers/ActionSelectorCacheItem.cs, test/Microsoft.AspNet.WebApi.Versioning.Tests/Dispatcher/ApiVersionControllerSelectorTest.cs, test/Microsoft.AspNet.WebApi.Versioning.Tests/Simulators/AdminController.cs
Fixed the internal action selection process to consider both convention and attributing routing. The resolution process is now progressive rather than unioned. This avoids a smaller number of cases that cause duplicate actions to be resolves when then shouldn't be.
=> Fix Internal Action Selection

src/Microsoft.AspNet.OData.Versioning/System.Web.Http/HttpConfigurationExtensions.cs, src/Microsoft.AspNet.OData.Versioning/System.Web.Http/HttpRequestMessageExtensions.cs, src/Microsoft.AspNet.OData.Versioning/Web.OData/Builder/VersionedODataModelBuilder.cs, src/Microsoft.AspNet.OData.Versioning/Web.OData/Controllers/VersionedMetadataController.cs, src/Microsoft.AspNet.OData.Versioning/Web.OData/Routing/UnversionedODataPathRouteConstraint.cs, src/Microsoft.AspNet.OData.Versioning/Web.OData/Routing/VersionedODataPathRouteConstraint.cs, src/Microsoft.AspNet.OData.Versioning/Web.OData/Routing/VersionedUrlHelperDecorator.cs, src/Microsoft.AspNet.WebApi.Versioning/Dispatcher/HttpResponseExceptionFactory.cs, src/Microsoft.AspNet.WebApi.Versioning/Routing/ApiVersionRouteConstraint.cs, test/Microsoft.AspNet.OData.Versioning.Tests/System.Web.OData/HttpConfigurationExtensionsTest.cs, test/Microsoft.AspNet.OData.Versioning.Tests/Web.OData/Controllers/VersionedMetadataControllerTest.cs, test/Microsoft.AspNet.OData.Versioning.Tests/Web.OData/Routing/VersionedODataPathRouteConstraintTest.cs, test/Microsoft.AspNet.WebApi.Versioning.Tests/Dispatcher/ApiVersionControllerSelectorTest.cs, test/Microsoft.AspNet.WebApi.Versioning.Tests/Routing/ApiVersionRouteConstraintTest.cs
Provides the fix for returning 400 instead of 404 for OData controllers that exist, but don't match the requested API version. This change also fixes an issue discovered where URL generation fails for URL segment API versioning due to a bug in the ApiVersionRouteConstraint.
=> Fix for OData 404 Instead of 400

src/Microsoft.AspNetCore.Mvc.Versioning/Routing/ApiVersionRouteConstraint.cs, src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersionActionSelector.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Routing/ApiVersionRouteConstraintTest.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Simulators/OrdersController.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Versioning/ApiVersionActionSelectorTest.cs
This fix correctly returns generated URLs and 400s as appropriate when using URL segment API versioning.
=> Fix for ASP.NET Core URL Generation and 404

src/Microsoft.AspNet.WebApi.Versioning/Dispatcher/ApiVersionControllerAggregator.cs, src/Microsoft.AspNet.WebApi.Versioning/Dispatcher/HttpControllerTypeCache.cs
Provides the fix to correctly report the aggregated API versions across controllers when versioning by URL segment with the ApiVersionRouteConstraint.
=> Fix for Reported API Versions using URL Segment

src/Microsoft.AspNet.WebApi.Versioning/Controllers/ActionSelectorCacheItem.cs, src/Microsoft.AspNet.WebApi.Versioning/Controllers/AggregatedActionMapping.cs, src/Microsoft.AspNet.WebApi.Versioning/Controllers/ApiVersionActionSelector.cs, src/Microsoft.AspNet.WebApi.Versioning/Dispatcher/ConventionRouteControllerSelector.cs, src/Microsoft.AspNet.WebApi.Versioning/System.Web.Http/HttpControllerDescriptorExtensions.cs
This fix returns 400 for actions unsupported in some service API versions instead of returning 404.
=> Fix to Return 400 Instead of 404 for Versioned Actions

samples/webapi/BasicODataWebApiSample/Controllers/People2Controller.cs, src/Microsoft.AspNet.OData.Versioning/Web.OData/Routing/VersionedAttributeRoutingConvention.cs, src/Microsoft.AspNet.OData.Versioning/Web.OData/Routing/VersionedODataPathRouteConstraint.cs, src/Microsoft.AspNet.OData.Versioning/project.json, test/Microsoft.AspNet.OData.Versioning.Tests/Web.OData/Routing/VersionedAttributeRoutingConventionTest.cs
- Fixes the route template parameter name used in OData route templates
- Updates the NuGet package to limit forward to support to < 6.0.0
- Minor update to sample project for consistency
=> Fixes OData route template parameter name binding

src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersionActionSelector.cs, test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/ByNamespace/Controllers/V1/AgreementsController.cs, test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/ByNamespace/Controllers/V2/AgreementsController.cs, test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/ByNamespace/Controllers/V3/AgreementsController.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Simulators/AmbiguousController.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Simulators/AmbiguousNeutralController.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Simulators/AmbiguousToo2Controller.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Simulators/AmbiguousTooController.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Simulators/ApiVersionedRoute2Controller.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Simulators/ApiVersionedRouteController.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Simulators/AttributeRoutedAmbiguous2Controller.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Simulators/AttributeRoutedAmbiguous3Controller.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Simulators/AttributeRoutedAmbiguousController.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Simulators/AttributeRoutedAmbiguousNeutralController.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Simulators/AttributeRoutedTest2Controller.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Simulators/AttributeRoutedTest4Controller.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Simulators/AttributeRoutedTestController.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Simulators/AttributeRoutedVersionNeutralController.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Simulators/ConventionsController.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Simulators/NeutralController.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Simulators/TestController.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Simulators/TestVersion2Controller.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Versioning/ApiVersionActionSelectorTest.cs
Addresses a scenario where the matched action results are null when no actions and their constraints are matched. The ApiVersionActionSelector should subsequently return null to propagate a HTTP 404 response.
=> Fix ArgumentNullException in ApiVersionActionSelector

ApiVersioning.sln, ApiVersioningWithSamples.sln, src/Common/Versioning/Conventions/ActionApiVersionConventionBuilderCollectionT.cs, src/Common/Versioning/Conventions/ControllerApiVersionConventionBuilderT.cs, src/Microsoft.AspNet.OData.Versioning/project.json, src/Microsoft.AspNet.WebApi.Versioning/Versioning/Conventions/ActionApiVersionConventionBuilderCollectionT.cs, src/Microsoft.AspNet.WebApi.Versioning/Versioning/Conventions/ControllerApiVersionConventionBuilderT.cs, src/Microsoft.AspNet.WebApi.Versioning/project.json, src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/Conventions/ActionApiVersionConventionBuilderCollectionT.cs, src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/Conventions/ControllerApiVersionConventionBuilderT.cs, src/Microsoft.AspNetCore.Mvc.Versioning/project.json, test/Microsoft.AspNet.WebApi.Versioning.Tests/Versioning/Conventions/ControllerApiVersionConventionBuilderTTest.cs, test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Conventions/given/a_query_string_versioned_Controller_split_into_two_types_using_conventions.cs, test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Conventions/given/a_url_versioned_Controller_using_conventions.cs
Addresses an issue where controller actions are not always correctly mapped to the default API version conventions as well as resolves a few flaky tests.
=> Fix Mapping of Controller Actions to API Version Conventions

src/Common/Common.projitems, src/Common/Versioning/ErrorCodes.cs, src/Common/Versioning/ErrorResponseContext.cs, src/Common/Versioning/IErrorResponseProvider.cs, src/Microsoft.AspNet.WebApi.Versioning/Dispatcher/ApiVersionControllerSelector.cs, src/Microsoft.AspNet.WebApi.Versioning/Dispatcher/HttpResponseExceptionFactory.cs, src/Microsoft.AspNet.WebApi.Versioning/IErrorResponseProviderExtensions.cs, src/Microsoft.AspNet.WebApi.Versioning/Versioning/DefaultErrorResponseProvider.cs, src/Microsoft.AspNet.WebApi.Versioning/Versioning/ErrorResponseContext.cs, src/Microsoft.AspNetCore.Mvc.Versioning/IErrorResponseProviderExtensions.cs, src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersionActionSelector.cs, src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/BadRequestHandler.cs, src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/DefaultErrorResponseProvider.cs, src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ErrorResponseContext.cs, src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/MethodNotAllowedHandler.cs
Refactors and simplifies the IErrorResponseProvider. The ErrorResponseContext now provides the default HTTP status code. An ErrorCodes type is now provided with the set of constant error codes returned in error response. These two pieces of information should allow customizations to error responses such as 404 and 406 depending on the API versioning method.
=> Simplify Error Response Provider

src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/CollectionExtensions.cs, src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/Description/VersionedApiExplorer.cs, src/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer/DefaultApiVersionDescriptionProvider.cs, src/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer/VersionedApiDescriptionProvider.cs, test/Microsoft.AspNet.WebApi.Versioning.ApiExplorer.Tests/Description/TestConfigurations.cs, test/Microsoft.AspNet.WebApi.Versioning.ApiExplorer.Tests/Description/VersionedApiExplorerTest.cs, test/Microsoft.AspNet.WebApi.Versioning.ApiExplorer.Tests/Simulators/AttributeValues2Controller.cs, test/Microsoft.AspNet.WebApi.Versioning.ApiExplorer.Tests/Simulators/Values2Controller.cs, test/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer.Tests/DefaultApiVersionDescriptionProviderTest.cs, test/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer.Tests/VersionedApiDescriptionProviderTest.cs
This PR fixes:
* Wrong HttpActionDescriptor is discovered in the ApiDescription when actions have the same name and API versions are interleaved (#117)
* Discovery of API version-neutral controllers and actions (#118)
* The default API version is discovered if no other API versions are found
=> API Explorer Fixes (Beta 1)

src/Microsoft.AspNet.WebApi.Versioning/Controllers/ActionSelectorCacheItem.cs, test/Microsoft.AspNet.WebApi.Acceptance.Tests/AcceptanceTest.cs, test/Microsoft.AspNet.WebApi.Acceptance.Tests/TraceWriter.cs, test/Microsoft.AspNet.WebApi.Versioning.ApiExplorer.Tests/Description/TestConfigurations.cs
Corrects the matching of API versioned actions when an ITraceWriter is used. Acceptance tests and API explorer tests are updated to include a stub ITraceWriter to ensure there are no regressions. This PR fixes #119.
=> Fix API Versioning When ITraceWriter Is Used

ApiVersioningWithSamples.sln, src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersionActionSelector.cs, test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Basic/BasicAcceptanceTest.cs, test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Basic/Controllers/PingController.cs, test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Basic/Controllers/WithViewsUsingAttributes/HomeController.cs, test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Basic/Controllers/WithViewsUsingConventions/HomeController.cs, test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Basic/given a version-neutral Controller/when no version is specified.cs, test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Basic/given a version-neutral UI Controller/when accessing a view using attribute routing.cs, test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Basic/given a version-neutral UI Controller/when accessing a view using convention routing.cs
Fixes routing for MVC views in ASP.NET Core 1.1 RC2 by copying the route values from matches into the results evaluated by the api versioning policy. Fixes #130.
=> Fix MVC Routing in 1.1 RC2

src/Microsoft.AspNetCore.Mvc.Versioning/Microsoft.AspNetCore.Mvc.Versioning.csproj, src/Microsoft.AspNetCore.Mvc.Versioning/Routing/DefaultApiVersionRoutePolicy.cs, src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersionActionSelector.cs, test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Basic/Controllers/OverlappingRouteTemplateController.cs, test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Basic/given a versioned Controller/when two route templates overlap.cs
Fixes scenarios in ASP.NET Core where action selection may be incorrect when multiple actions have overlapping route templates (ex: /resources/{id} and /resources/search). Depending on the order in which the routes are requested, the wrong action might be selected because precendence of a better match was not considered. This will fix #148 and likely #147.
=> Fix Action Selection for Routes with Overlapping Templates

src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/Description/ApiVersionParameterDescriptionContext.cs, src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/LocalSR.Designer.cs, src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/LocalSR.resx, src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/Microsoft.AspNet.WebApi.Versioning.ApiExplorer.csproj, src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/System.Web.Http/MediaTypeFormatterAdapterFactory.cs, test/Microsoft.AspNet.WebApi.Versioning.ApiExplorer.Tests/Description/ApiVersionParameterDescriptionContextTest.cs
Improves the process for automatically cloning MediaTypeFormatter instances by supporting parameterless constructors as well. The cloning process is required by the API explorer for Web API when API versioning is performed by media type.
=> Improve Cloning of MediaTypeFormatter

src/Microsoft.AspNetCore.Mvc.Versioning/Microsoft.AspNetCore.Mvc.Versioning.csproj, src/Microsoft.AspNetCore.Mvc.Versioning/Routing/DefaultApiVersionRoutePolicy.cs, src/Microsoft.AspNetCore.Mvc.Versioning/SR.Designer.cs, src/Microsoft.AspNetCore.Mvc.Versioning/SR.resx, test/Microsoft.AspNet.WebApi.Acceptance.Tests/Http/Basic/given a version-neutral ApiController/when no version is specified.cs, test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Basic/given a version-neutral Controller/when no version is specified.cs
Updates route handling for API version-neutral routes to correctly return 405 when the only reason they are not matched is due to an unsupported HTTP method.
=> Fix 405 Handling for API Version-Neutral Routes

src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/Description/ApiVersionParameterDescriptionContext.cs, src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/Microsoft.AspNet.WebApi.Versioning.ApiExplorer.csproj, src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/System.Web.Http/MediaTypeFormatterAdapterFactory.cs, test/Microsoft.AspNet.WebApi.Versioning.ApiExplorer.Tests/Description/ApiVersionParameterDescriptionContextTest.cs
The existing cloning support for MediaTypeFormatter instances does not correctly clone the SupportedMediaTypes collection when cloning instances using a discovered copy constructor.
This PR adds some additional Reflection hackery to clone the media type values per formatter, per documented API version.
=> Fix Cloning of MediaTypeFormatter.SupportedMediaTypes

src/Microsoft.AspNetCore.Mvc.Versioning/Routing/DefaultApiVersionRoutePolicy.cs
This fix includes a simple update the assigns the matched RouteData to the RouteContext. This will ensure that the RouteData is handed over to the IRoutingFeature exposed through the HttpContext.
This change has no effect on the ActionContext or ControllerContext, which already contained the correct RouteData. Fixes #176.
=> Fix RouteData Used By Routing Feature

src/Microsoft.AspNet.OData.Versioning.ApiExplorer/Description/ODataRouteBuilder.cs
Correctly build the route parameter for the "key" parameter when routing by convention. Fixes #226
=> Fix OData API Explorer Convention-Generated URLs

samples/aspnetcore/SwaggerSample/Startup.cs, samples/aspnetcore/SwaggerSample/SwaggerDefaultValues.cs, samples/webapi/SwaggerODataWebApiSample/Startup.cs, samples/webapi/SwaggerWebApiSample/Startup.cs, src/Common.ApiExplorer/ApiExplorerOptions.cs, src/Microsoft.AspNet.OData.Versioning.ApiExplorer/Microsoft.AspNet.OData.Versioning.ApiExplorer.csproj, src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/Description/VersionedApiExplorer.cs, src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/Microsoft.AspNet.WebApi.Versioning.ApiExplorer.csproj, src/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer/ApiVersionParameterDescriptionContext.cs, src/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer.csproj, src/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer/VersionedApiDescriptionProvider.cs
Adds support to substitute the API versions in URLs from route templates in API descriptions generated by API Explorers. This change also contains a fix for a NullReferenceException when a parameter does not have model metadata (ASP.NET Core only).
Resolves #247. Fixes #250.
=> Support URL Substitution in API Explorer

src/Microsoft.AspNetCore.Mvc.Versioning/ReportApiVersionsAttribute.cs, src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ActionDescriptorMatch.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/ReportApiVersionsAttributeTest.cs
Fixes scenarios in ASP.NET Core where the API versions cannot be reported in the HTTP response headers because the response is already being written to the client.
Fixes #273. Fixes #290.
=> Fix API Version Reporting

.editorconfig, build/common.props, src/Microsoft.AspNetCore.Mvc.Versioning/Abstractions/ActionDescriptorExtensions.cs, src/Microsoft.AspNetCore.Mvc.Versioning/Microsoft.Extensions.DependencyInjection/IServiceCollectionExtensions.cs, src/Microsoft.AspNetCore.Mvc.Versioning/Routing/DefaultApiVersionRoutePolicy.cs, src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersionActionSelector.cs, src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersionCollator.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Versioning/ApiVersionActionSelectorTest.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Versioning/ApiVersionCollatorTest.cs
Refactor API version model aggregation to be pre-computed and supplants the need to modify action property bags at runtime. Fixes #306.
=> Pre-Aggregate API Version Models

src/Microsoft.AspNet.OData.Versioning.ApiExplorer/Microsoft.AspNet.OData.Versioning.ApiExplorer.csproj, src/Microsoft.AspNet.OData.Versioning.ApiExplorer/System.Web.Http/HttpRouteCollectionExtensions.cs
Fix route name lookup when hosted in IIS. This only occurs when using OData and the application is hosted in IIS. Fixes #302.
=> Fix OData route name lookup when hosted in IIS

.gitignore, ApiVersioning.v3.ncrunchsolution, src/Common/Common.projitems, src/Common/UriExtensions.cs, src/Microsoft.AspNet.WebApi.Versioning/Dispatcher/HttpResponseExceptionFactory.cs, src/Microsoft.AspNetCore.Mvc.Versioning/Routing/DefaultApiVersionRoutePolicy.cs, test/Microsoft.AspNet.WebApi.Acceptance.Tests/OData/Basic/BasicAcceptanceTest.cs, test/Microsoft.AspNet.WebApi.Versioning.Tests/Dispatcher/ApiVersionControllerSelectorTest.cs, test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Mvc/Basic/given a version-neutral Controller/when no version is specified.cs, test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/OData/Basic/BasicAcceptanceTest.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/Versioning/ApiVersionActionSelectorTest.cs
To avoid xss reflection attach, the error messages will now render the absolute path omitting the query string
=> avoid reflecting the query string

src/Common.OData.ApiExplorer/AspNet.OData/ClassProperty.cs, src/Common.OData.ApiExplorer/AspNet.OData/DeclaringType.cs, src/Common.OData.ApiExplorer/AspNet.OData/DefaultModelTypeBuilder.cs, src/Common.OData.ApiExplorer/AspNet.OData/PropertyDependency.cs, src/Common.OData.ApiExplorer/AspNet.OData/TypeExtensions.cs, src/Common.OData.ApiExplorer/Common.OData.ApiExplorer.projitems, test/Microsoft.AspNet.OData.Versioning.ApiExplorer.Tests/AspNet.OData/DefaultModelTypeBuilderTest.cs, test/Microsoft.AspNet.OData.Versioning.ApiExplorer.Tests/AspNet.OData/Employee.cs, test/Microsoft.AspNet.OData.Versioning.ApiExplorer.Tests/AspNet.OData/Employer.cs, test/Microsoft.AspNetCore.OData.Versioning.ApiExplorer.Tests/AspNet.OData/DefaultModelTypeBuilderTest.cs, test/Microsoft.AspNetCore.OData.Versioning.ApiExplorer.Tests/AspNet.OData/Employee.cs, test/Microsoft.AspNetCore.OData.Versioning.ApiExplorer.Tests/AspNet.OData/Employer.cs
Allow the substitution of structured types that have references to types that are still being built.
This supports self-references but also adds support for backreferences or circular references.
Removed the NewStructuredTypeOrSelf methods because the dependency resolver will handle this now.
Note: I removed the type_should_match_with_self_referencing_property_substition test because with the current implementation if there is a self-reference or back reference the type will always be dynamically built.
=> Support substitution with dependencies

src/Common.OData.ApiExplorer/AspNet.OData/ClassProperty.cs, src/Common.OData.ApiExplorer/AspNet.OData/DefaultModelTypeBuilder.cs, src/Common.OData.ApiExplorer/AspNet.OData/IModelTypeBuilder.cs, src/Microsoft.AspNet.OData.Versioning.ApiExplorer/AspNet.OData/Routing/ODataRouteBuilderContext.cs, src/Microsoft.AspNetCore.OData.Versioning.ApiExplorer/AspNetCore.Mvc.ApiExplorer/PseudoModelBindingVisitor.cs, test/Microsoft.AspNet.OData.Versioning.ApiExplorer.Tests/AspNet.OData/DefaultModelTypeBuilderTest.cs, test/Microsoft.AspNet.OData.Versioning.ApiExplorer.Tests/AspNet.OData/Employer.cs, test/Microsoft.AspNetCore.OData.Versioning.ApiExplorer.Tests/AspNet.OData/DefaultModelTypeBuilderTest.cs, test/Microsoft.AspNetCore.OData.Versioning.ApiExplorer.Tests/AspNet.OData/Employer.cs
Just a little thing I noticed while testing. ODataActionParameters with collection parameters would cause the type in the ClassProperty to be null. This caused an exception when trying to generate the type for the parameters.
I also fixed some misplaced using directives from my previous PR.
=> Add support for action parameters with collection parameters

src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/Description/ApiVersionParameterDescriptionContext.cs, test/Microsoft.AspNet.WebApi.Versioning.ApiExplorer.Tests/Description/ApiVersionParameterDescriptionContextTest.cs
Make updating the API version parameter description for a path route parameter reliable in Web API. Related #419
=> Improve Explorer API Version From Path in Web API

src/Common.OData.ApiExplorer/AspNet.OData/DefaultModelTypeBuilder.cs, src/Microsoft.AspNet.OData.Versioning.ApiExplorer/Microsoft.AspNet.OData.Versioning.ApiExplorer.csproj, src/Microsoft.AspNet.OData.Versioning.ApiExplorer/ReleaseNotes.txt, src/Microsoft.AspNetCore.OData.Versioning.ApiExplorer/Microsoft.AspNetCore.OData.Versioning.ApiExplorer.csproj, src/Microsoft.AspNetCore.OData.Versioning.ApiExplorer/ReleaseNotes.txt, test/Microsoft.AspNet.OData.Versioning.ApiExplorer.Tests/AspNet.OData/DefaultModelTypeBuilderTest.cs, test/Microsoft.AspNet.OData.Versioning.ApiExplorer.Tests/AspNet.OData/Shipment.cs, test/Microsoft.AspNetCore.OData.Versioning.ApiExplorer.Tests/AspNet.OData/DefaultModelTypeBuilderTest.cs, test/Microsoft.AspNetCore.OData.Versioning.ApiExplorer.Tests/AspNet.OData/Shipment.cs
This is was a small oversight where types that have properties referencing other types that matched the edm would never resolve their property. This caused the type to never be resolved and throw an exception when being explored.
=> Fixed type builder not keeping track of clrtypes that match the edm

src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/System.Web.Http/Description/ApiDescriptionExtensions.cs, src/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer/ApiDescriptionExtensions.cs, test/Microsoft.AspNet.WebApi.Versioning.ApiExplorer.Tests/System.Web.Http/Description/ApiDescriptionExtensionsTest.cs, test/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer.Tests/ApiDescriptionExtensionsTest.cs
Add an extension method for determining whether an ApiDescription is deprecated. Related to #441.
NOTE: This is possible to do today, but you have to know how to do it. This extension method simplifies the requirement for developers.
=> Add IsDeprecated Extension Method

src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/System.Web.Http/Description/ApiDescriptionExtensions.cs, src/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer/ApiDescriptionExtensions.cs, test/Microsoft.AspNet.WebApi.Versioning.ApiExplorer.Tests/System.Web.Http/Description/ApiDescriptionExtensionsTest.cs, test/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer.Tests/ApiDescriptionExtensionsTest.cs
Add an IsDeprecated extension method, which will simplify API Explorer use such as in Swagger document generation. Related to #441.
=> Add an IsDeprecated Extension Method

src/Common/Common.projitems, src/Common/Versioning/IApiVersionReaderExtensions.cs, src/Common/Versioning/MediaTypeApiVersionReader.cs, src/Microsoft.AspNet.WebApi.Versioning/Microsoft.AspNet.WebApi.Versioning.csproj, src/Microsoft.AspNet.WebApi.Versioning/ReleaseNotes.txt, src/Microsoft.AspNet.WebApi.Versioning/System.Web.Http/HttpConfigurationExtensions.cs, src/Microsoft.AspNet.WebApi.Versioning/Versioning/ApplyContentTypeVersionActionFilter.cs, src/Microsoft.AspNetCore.Mvc.Versioning/Microsoft.AspNetCore.Mvc.Versioning.csproj, src/Microsoft.AspNetCore.Mvc.Versioning/Microsoft.Extensions.DependencyInjection/IServiceCollectionExtensions.cs, src/Microsoft.AspNetCore.Mvc.Versioning/ReleaseNotes.txt, src/Microsoft.AspNetCore.Mvc.Versioning/ReportApiVersionsAttribute.cs, src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersioningMvcOptionsSetup.cs, src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApplyContentTypeVersionActionFilter.cs, test/Microsoft.AspNet.WebApi.Acceptance.Tests/Http/MediaTypeNegotiation/given a versioned ApiController/when using media type negotiation.cs, test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Mvc/MediaTypeNegotiation/given a versioned Controller/when using media type negotiation.cs, test/Microsoft.AspNetCore.Mvc.Versioning.Tests/ReportApiVersionsAttributeTest.cs
Adds support to return the API version in the **Content-Type** HTTP header when versioning by media type. Also contains a minor optimization when writing API Versioning response headers.
=> Return API Version in Media Type

src/Common.OData.ApiExplorer/AspNet.OData/Routing/ODataRouteBuilder.cs, src/Common.OData.ApiExplorer/AspNet.OData/TypeExtensions.cs, src/Microsoft.AspNet.OData.Versioning.ApiExplorer/Microsoft.AspNet.OData.Versioning.ApiExplorer.csproj, src/Microsoft.AspNet.OData.Versioning.ApiExplorer/ReleaseNotes.txt, src/Microsoft.AspNetCore.Mvc.Versioning/Microsoft.AspNetCore.Mvc.Versioning.csproj, src/Microsoft.AspNetCore.Mvc.Versioning/ReleaseNotes.txt, src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersioningApplicationModelProvider.cs, src/Microsoft.AspNetCore.OData.Versioning.ApiExplorer/AspNetCore.Mvc.ApiExplorer/ODataApiDescriptionProvider.cs, src/Microsoft.AspNetCore.OData.Versioning.ApiExplorer/Microsoft.AspNetCore.OData.Versioning.ApiExplorer.csproj, src/Microsoft.AspNetCore.OData.Versioning.ApiExplorer/ReleaseNotes.txt, src/Microsoft.AspNetCore.OData.Versioning/AspNetCore.Mvc/Versioning/ApiExplorerModelConvention.cs, src/Microsoft.AspNetCore.OData.Versioning/Microsoft.AspNetCore.OData.Versioning.csproj, src/Microsoft.AspNetCore.OData.Versioning/ReleaseNotes.txt
Adds various minor OData fixes, primarily to the API Explorer.
=> OData Fixes July 2019

samples/aspnetcore/ODataBasicSample/Startup.cs, samples/aspnetcore/SwaggerODataSample/Startup.cs, samples/webapi/SwaggerODataWebApiSample/Startup.cs, samples/webapi/SwaggerWebApiSample/Startup.cs, src/Common.OData.ApiExplorer/AspNet.OData/Routing/ODataRouteBuilder.cs, src/Common.OData.ApiExplorer/AspNet.OData/Routing/ODataRouteBuilderContext.cs, src/Microsoft.AspNet.OData.Versioning.ApiExplorer/AspNet.OData/Routing/ODataRouteBuilderContext.cs, src/Microsoft.AspNet.OData.Versioning.ApiExplorer/Microsoft.AspNet.OData.Versioning.ApiExplorer.csproj, src/Microsoft.AspNet.OData.Versioning.ApiExplorer/ReleaseNotes.txt, src/Microsoft.AspNet.OData.Versioning.ApiExplorer/System.Web.Http/HttpConfigurationExtensions.cs, src/Microsoft.AspNet.OData.Versioning/Microsoft.AspNet.OData.Versioning.csproj, src/Microsoft.AspNet.OData.Versioning/ReleaseNotes.txt, src/Microsoft.AspNet.OData.Versioning/System.Web.Http/IContainerBuilderExtensions.cs, src/Microsoft.AspNetCore.OData.Versioning.ApiExplorer/AspNet.OData/Routing/ODataRouteBuilderContext.cs, src/Microsoft.AspNetCore.OData.Versioning.ApiExplorer/Microsoft.AspNetCore.OData.Versioning.ApiExplorer.csproj, src/Microsoft.AspNetCore.OData.Versioning.ApiExplorer/ReleaseNotes.txt, src/Microsoft.AspNetCore.OData.Versioning/AspNet.OData/Routing/ODataRouteBuilderContext.Core.cs, src/Microsoft.AspNetCore.OData.Versioning/Microsoft.AspNetCore.OData.Versioning.csproj, src/Microsoft.AspNetCore.OData.Versioning/ReleaseNotes.txt, test/Microsoft.AspNetCore.OData.Versioning.ApiExplorer.Tests/AspNetCore.Mvc.ApiExplorer/ODataApiDescriptionProviderTest.cs, test/directory.build.props
Summary of fixes:
- Fix regression in OData 7.2 when registering default services; requires Reflection once again
- Fix _key as segment_ URL generation
- Update default key delimiter to match OData default, which is now slash
- Update sample projects
=> OData Fixes 2019-08-07

src/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer/ApiVersionDescription.cs
When some API versions are partially deprecated, IsDeprecated returns false (not true).
=> correct ApiVersionDescription.IsDeprecated docs

samples/aspnetcore/SwaggerODataSample/SwaggerDefaultValues.cs, samples/aspnetcore/SwaggerSample/SwaggerDefaultValues.cs
=> Added Swagger support for OData void response type and default parameter values other than strings

src/Microsoft.AspNetCore.OData.Versioning/AspNetCore.Mvc/Versioning/ODataApiVersionActionSelector.cs
I created custom routing conventions (via https://docs.microsoft.com/en-us/odata/webapi/custom-routing-convention) to allow "PATCH /entityset" and "PUT /entityset".
These require collections of entities to be passed to the function, and they were getting held up during action selection. This small update corrects it for my edge case.
=> Allow ICollectionModelBinder as registered parameters

asp.sln, examples/AspNetCore/OData/Directory.Build.props, src/AspNet/WebApi/src/Asp.Versioning.WebApi.ApiExplorer/ApiExplorer/VersionedApiExplorer.cs, src/AspNetCore/OData/src/Asp.Versioning.OData.ApiExplorer/ApiExplorer/ODataApiDescriptionProvider.cs, src/AspNetCore/OData/src/Asp.Versioning.OData/Asp.Versioning.OData.csproj, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/ApiDescriptionExtensions.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/ApiVersionParameterDescriptionContext.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/DependencyInjection/IApiVersioningBuilderExtensions.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/VersionedApiDescriptionProvider.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/Abstractions/ActionDescriptorExtensions.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/ApiVersionCollator.cs, src/Common/src/Common/DefaultApiVersionReporter.cs
Fixes issues reported in 6.0 Preview 3:
- #823 
- #830 
- #837 
- #839
=> 6.0 Preview 3 Fixes

src/AspNetCore/OData/src/Asp.Versioning.OData.ApiExplorer/Asp.Versioning.OData.ApiExplorer.csproj, src/AspNetCore/OData/src/Asp.Versioning.OData/Asp.Versioning.OData.csproj, src/AspNetCore/OData/src/Asp.Versioning.OData/OData/VersionedODataTemplateTranslator.cs, src/AspNetCore/OData/src/Asp.Versioning.OData/ReleaseNotes.txt, src/AspNetCore/WebApi/src/Asp.Versioning.Http/ApiExplorer/ApiVersionMetadataCollationCollection.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Http/ApiExplorer/ApiVersionMetadataCollationContext.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Http/ApiExplorer/EndpointApiVersionMetadataCollationProvider.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Http/ApiExplorer/IApiVersionMetadataCollationProvider.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Http/Asp.Versioning.Http.csproj, src/AspNetCore/WebApi/src/Asp.Versioning.Http/DependencyInjection/IServiceCollectionExtensions.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Http/ReleaseNotes.txt, src/AspNetCore/WebApi/src/Asp.Versioning.Http/Routing/ApiVersionMatcherPolicy.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/Asp.Versioning.Mvc.ApiExplorer.csproj, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/DefaultApiVersionDescriptionProvider.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/GroupedApiVersionDescriptionProvider.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/ReleaseNotes.txt, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/VersionedApiDescriptionProvider.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/ApiExplorer/ActionApiVersionMetadataCollationProvider.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/ApiVersionCollator.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/Asp.Versioning.Mvc.csproj, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/DependencyInjection/IApiVersioningBuilderExtensions.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/ReleaseNotes.txt, src/AspNetCore/WebApi/test/Asp.Versioning.Mvc.ApiExplorer.Tests/TestActionDescriptorCollectionProvider.cs, src/AspNetCore/WebApi/test/Asp.Versioning.Mvc.ApiExplorer.Tests/VersionedApiDescriptionProviderTest.cs
Patch containing hot fixes for:
- Fixes #922
- Fixes #923
- OData 723
=> 6.3.1 Fixes

src/Abstractions/src/Asp.Versioning.Abstractions/AdvertiseApiVersionsAttribute.cs, src/Abstractions/src/Asp.Versioning.Abstractions/Asp.Versioning.Abstractions.csproj, src/Abstractions/src/Asp.Versioning.Abstractions/ReleaseNotes.txt, src/Abstractions/test/Asp.Versioning.Abstractions.Tests/ApiVersionFormatProviderTest.cs, src/Abstractions/test/Asp.Versioning.Abstractions.Tests/AssumeCultureAttribute.cs
Fixes a stack overflow bug and updates tests to always run under `en-US`
Fixes #932
=> Fix Stack Overflow

src/AspNet/OData/src/Asp.Versioning.WebApi.OData.ApiExplorer/Asp.Versioning.WebApi.OData.ApiExplorer.csproj, src/AspNet/OData/src/Asp.Versioning.WebApi.OData.ApiExplorer/ReleaseNotes.txt, src/AspNetCore/OData/src/Asp.Versioning.OData.ApiExplorer/Asp.Versioning.OData.ApiExplorer.csproj, src/AspNetCore/OData/src/Asp.Versioning.OData.ApiExplorer/ReleaseNotes.txt, src/AspNetCore/OData/test/Asp.Versioning.OData.ApiExplorer.Tests/Conventions/ODataValidationSettingsConventionTest.cs, src/Common/src/Common.OData.ApiExplorer/Conventions/ODataAttributeVisitor.cs
Reorders OData query option visitation such that `EnableQueryAttribute` settings override any previous _Model Bound_ settings.
- Related to #928
=> EnableQueryAttribute Should Override Model Bound Settings

src/AspNet/OData/src/Asp.Versioning.WebApi.OData.ApiExplorer/Asp.Versioning.WebApi.OData.ApiExplorer.csproj, src/AspNet/OData/src/Asp.Versioning.WebApi.OData.ApiExplorer/ReleaseNotes.txt, src/AspNetCore/OData/src/Asp.Versioning.OData.ApiExplorer/Asp.Versioning.OData.ApiExplorer.csproj, src/AspNetCore/OData/src/Asp.Versioning.OData.ApiExplorer/ReleaseNotes.txt, src/AspNetCore/OData/test/Asp.Versioning.OData.ApiExplorer.Tests/Conventions/ODataValidationSettingsConventionTest.cs, src/Common/src/Common.OData.ApiExplorer/Conventions/ODataAttributeVisitor.cs
Backports the _Model Bound_ settings override change to .NET 6.0
- Related to #928
=> Backport Model Bound Setting Overrides

src/AspNet/OData/src/Asp.Versioning.WebApi.OData.ApiExplorer/Asp.Versioning.WebApi.OData.ApiExplorer.csproj, src/AspNet/OData/src/Asp.Versioning.WebApi.OData.ApiExplorer/ReleaseNotes.txt, src/AspNetCore/OData/src/Asp.Versioning.OData.ApiExplorer/Asp.Versioning.OData.ApiExplorer.csproj, src/AspNetCore/OData/src/Asp.Versioning.OData.ApiExplorer/ReleaseNotes.txt, src/Common/src/Common.OData.ApiExplorer/OData/ClassSignature.cs, src/Common/src/Common.OData.ApiExplorer/OData/DefaultModelTypeBuilder.cs, src/Common/src/Common.OData.ApiExplorer/OData/EdmModelKey.cs, src/Common/src/Common.OData.ApiExplorer/OData/EdmTypeKey.cs
Summary of the changes (Less than 80 chars)
- Fixes the scenario where there are multiple EDMs per API version, but they have different models
- Fixes a scenario that would otherwise prevent the use of a model in different EDMs for the same API version by using the name defined by the EDM, which otherwise defaults to the CLR type name
Fixes #996
=> Fixes Issue 996

src/AspNet/WebApi/src/Asp.Versioning.WebApi.ApiExplorer/ApiExplorer/ApiExplorerOptions.cs, src/AspNet/WebApi/src/Asp.Versioning.WebApi.ApiExplorer/Description/ApiVersionParameterDescriptionContext.cs, src/AspNet/WebApi/test/Asp.Versioning.WebApi.ApiExplorer.Tests/Description/ApiVersionParameterDescriptionContextTest.cs, src/AspNetCore/OData/src/Asp.Versioning.OData.ApiExplorer/ApiExplorer/ODataApiExplorerOptionsFactory.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/ApiExplorerOptions.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/ApiExplorerOptionsFactory{T}.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/ApiVersionParameterDescriptionContext.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/VersionedApiDescriptionProvider.cs, src/AspNetCore/WebApi/test/Asp.Versioning.Mvc.ApiExplorer.Tests/ApiVersionParameterDescriptionContextTest.cs, src/AspNetCore/WebApi/test/Asp.Versioning.Mvc.ApiExplorer.Tests/TestActionDescriptorCollectionProvider.cs, src/AspNetCore/WebApi/test/Asp.Versioning.Mvc.ApiExplorer.Tests/VersionedApiDescriptionProviderTest.cs, src/Common/src/Common.ApiExplorer/ApiExplorerOptions.cs
Addresses two distinct issues in the API Explorer implementations.
- Fixes #1025 
- Prefer explicit API descriptor over implicit match when ambiguous
- Leverage `IApiVersionSelector` to determine whether the first API version parameter should be optional
=> Issue 1025 Fix

.github/workflows/codeql-analysis.yml, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/ApiVersioningApplicationModelProvider.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/Asp.Versioning.Mvc.csproj, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/ReleaseNotes.txt
Summary of the changes (Less than 80 chars)
If Controller Attribute is set, use it for the controller's name
Fixes #1033
=> If Controller Attribute is set, use it for the controller's name

src/Abstractions/src/Asp.Versioning.Abstractions/Asp.Versioning.Abstractions.csproj, src/Abstractions/src/Asp.Versioning.Abstractions/ISunsetPolicyManagerExtensions.cs, src/Abstractions/src/Asp.Versioning.Abstractions/ReleaseNotes.txt, src/Abstractions/test/Asp.Versioning.Abstractions.Tests/ISunsetPolicyManagerExtensionsTest.cs, src/Common/src/Common/DefaultApiVersionReporter.cs
Correct sunset policy resolution when falling back
- Fixes #1064
=> Correct sunset policy resolution when falling back

src/AspNetCore/WebApi/src/Asp.Versioning.Http/ApiExplorer/DefaultEndpointInspector.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Http/ApiExplorer/EndpointApiVersionMetadataCollationProvider.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Http/ApiExplorer/IEndpointInspector.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Http/DependencyInjection/IServiceCollectionExtensions.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/ApiVersionDescriptionProviderFactory.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/DefaultApiVersionDescriptionProvider.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/DependencyInjection/IApiVersioningBuilderExtensions.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/GroupedApiVersionDescriptionProvider.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/Internal/ApiVersionDescriptionCollection.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/Internal/ApiVersionDescriptionComparer.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/Internal/DescriptionProvider.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/Internal/GroupedApiVersion.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/Internal/IGroupedApiVersionMetadata.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/Internal/IGroupedApiVersionMetadataFactory.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/ApiExplorer/MvcEndpointInspector.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc/DependencyInjection/IApiVersioningBuilderExtensions.cs
Fixes incorrect API version groups when a only a group name is defined.
- Add `IEndpointInspector` to determine if an `Endpoint` is for a controller action
- Fix/unify group reporting for `DefaultApiVersionDescriptionProvider` and `GroupedApiVersionDescriptionProvider`
- Fixes #1066
=> Fix Reported API Version Groups

src/Client/src/Asp.Versioning.Http.Client/ApiVersionEnumerator.cs, src/Client/src/Asp.Versioning.Http.Client/Asp.Versioning.Http.Client.csproj, src/Client/src/Asp.Versioning.Http.Client/ReleaseNotes.txt, src/Client/test/Asp.Versioning.Http.Client.Tests/ApiVersionEnumeratorTest.cs
Corrects parsing of API versions reported:
1. with a single value, in a single header
2. with a single value, in multiple headers
3. with multiple comma-separated values, in a single header
4. with multiple comma-separated values, in multiple headers
- Fixes #1070
=> Parse Single Header CSVs

src/AspNetCore/OData/src/Asp.Versioning.OData.ApiExplorer/ApiExplorer/ODataApiDescriptionProvider.cs, src/AspNetCore/OData/src/Asp.Versioning.OData.ApiExplorer/ApiExplorer/PartialODataDescriptionProvider.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/ApiDescriptionExtensions.cs, src/AspNetCore/WebApi/src/Asp.Versioning.Mvc.ApiExplorer/ApiVersionParameterDescriptionContext.cs
This PR adds support for OData collection parameters via the API Explorer for OData functions. The value format is unique to OData functions in the URL. OData actions can have collection parameters in the body as normal JSON arrays. The support **only** includes primitives, which includes enumerations. OData allows Complex Types, but that is not currently supported.
The issue of formatted or escaped string values cannot be solved. This is a limitation in OpenAPI. A user must input `string` values as `'text'` or `"text"` unless the author provides some other extension to the Swagger UI to handle _quoting_ of user input.
- Fixes #999 
- Improves performance of simple concatenation using `Span` rather than `string.Format`
=> Support OData Collection Parameters
